version: '3.0'
services:

  postgres_db:
    image: postgres:14.8-alpine3.18
    container_name: postgres_container
    environment:
      POSTGRES_USER: daniil
      POSTGRES_PASSWORD: 2428082
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
      
  redis_db:
    image: redis:alpine3.19
    container_name: redis_container
    ports:
      - "6379:6379"
  
  fastapi_app:
    build: .
    container_name: fastapi_container
    ports:
      - "8000:80"
    depends_on:
      - redis_db
      - postgres_db
